name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bin/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: "bin/package-lock.json"
      - run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: bin/
    steps:
      - name: Install pnpm
        run: sudo npm install -g pnpm
      - uses: actions/checkout@v3
      - name: Use Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: "bin/package-lock.json"
      - run: npm run test
